version: '3.8'

services:
  web:
    build: .
    command: waitress-serve --port=8000 crud_project.wsgi:application
    ports:
      - "8000:8000"
    environment:
      DATABASE_ENGINE: mssql
      DATABASE_NAME: library
      DATABASE_USER: sa
      DATABASE_PASSWORD: 123
      DATABASE_HOST: db
      DATABASE_PORT: 1433
    depends_on:
      - db

  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: "123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"