# Generated by Django 5.0.6 on 2024-06-08 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0003_alter_book_publisher'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='summary',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
